### ISSUE TITLE
Incorrect occupancy, construction mappings

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [shivamspj/AIR-CEDE-to-OED-file#10]
There are places, where occupancies and construction, were there are several values in AIR that map to 1 value in OED, are left as semi-colon separated values. These should be separated into two unique mappings. E.g. if 123;1234 in AIR maps to 4567 in OED. It means that 123 maps to 4567 and 1234 maps to 4567 (values are made up).
There are some values that have dashes in it, although there are none in the OED spec - please correct. Values with N/A in AIR should be removed, as these just indicate that there is no equivalent in AIR.
Please recheck the entire mapping tables that they are as per latest OED spec.

**Comment by shivamspj** [comment]
1. Checked construction codes file; removed ";" and "NA"  and added additional rows for many-to-one code mapping.
2. Verified occupancy codes and found no anomaly.
