### ISSUE TITLE
FlexiLocZZZ is included in the transformations

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [shivamspj/AIR-CEDE-to-OED-file#11]
FlexiLocZZZ is included in the OED spec to indicate that a number of fields can be added in the Loc file, as long as they start with FlexiLoc. E.g. if someone is interested in the colour of the house, they could add a field FlexiLocHouseColour as part of their loc file. I don't think it's relevant for CEDE to OED conversion and therefore should be removed.

**Comment by shivamspj** [comment]
Column found and removed from Location base file.
